### ISSUE TITLE
Nick colorization

### ISSUE THREAD

**Issue by kzisme** [SpaceLenore/thelounge-theme-dracula#3]
Hello!  I know using some different clients allow for custom scripts to colorize nicks.  In some cases while using `thelounge-theme-dracula` there are _many_ users with the same nick color making it hard to differentiate who is talking at times.

This is an addon for HexChat that accomplishes this: https://github.com/hexchat/hexchat-addons/blob/master/python/nicenicks/nicenicks.py

The "Default" thelounge theme handles colorization a little differently, but some possible changes that increase the pallet size, or randomness might be helpful.  (I know it's limited due to the style choices and such)

I am currently running thelounge v4.2.0 and the latest version of thelounge-theme-dracula

**Comment by SpaceLenore** [comment]
Hi!  
There are 32 available nick color classes in TheLounge and there's [only 11 colors in the Dracula theme](https://draculatheme.com/contribute) (but some colors are used as backgrounds, etc). I've distributed the 32 classes across the available colors instead of lumping them together in blocks. Exactly how TheLounge randomizes which user get what class is something I haven't looked into, perhaps there's a possibility to *slightly* increase the randomness by looking into that but it isn't feasible since with a limited palette there's bound to be lots of duplicates in larger channels.

Of course it would be possible to create lighter and darker shades of the base colors and use those for nicks but I'm quite happy the way it looks right now. (Feel free to fork and try it out, submit a PR if you think it looks good)

There's also [dracula/thelounge](https://www.npmjs.com/package/thelounge-theme-dracula-official) which has a different stylistic approach and seems to have more nick colors.
